/*
 * JSP generated by Resin-3.0.22 (built Mon, 13 Nov 2006 09:32:38 PST)
 */

package _jsp._template._test1;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _list__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=utf-8");
    request.setCharacterEncoding("UTF-8");
    com.caucho.jsp.IteratorLoopSupportTag _jsp_loop_0 = null;
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      if (_jsp_loop_0 == null)
        _jsp_loop_0 = new com.caucho.jsp.IteratorLoopSupportTag();
      java.util.Iterator _jsp_iter_1 = com.caucho.jstl.el.ForEachTag.getIterator(_caucho_expr_0.evalObject(pageContext));
      _jsp_loop_0.init(0, Integer.MAX_VALUE, 1);
      Object _jsp_oldVar_1 = pageContext.getAttribute("vo");
      while (_jsp_iter_1.hasNext()) {
        Object _jsp_i_1 = _jsp_iter_1.next();
        pageContext.setAttribute("vo", _jsp_i_1);
        _jsp_loop_0.setCurrent(_jsp_i_1, _jsp_iter_1.hasNext());
        out.write(_jsp_string1, 0, _jsp_string1.length);
        _caucho_expr_1.print(out, pageContext, false);
        out.write(_jsp_string2, 0, _jsp_string2.length);
        _caucho_expr_2.print(out, pageContext, false);
        out.write(_jsp_string2, 0, _jsp_string2.length);
        _caucho_expr_3.print(out, pageContext, false);
        out.write(_jsp_string2, 0, _jsp_string2.length);
        _caucho_expr_4.print(out, pageContext, false);
        out.write(_jsp_string2, 0, _jsp_string2.length);
        _caucho_expr_5.print(out, pageContext, false);
        out.write(_jsp_string2, 0, _jsp_string2.length);
        _caucho_expr_6.print(out, pageContext, false);
        out.write(_jsp_string2, 0, _jsp_string2.length);
        _caucho_expr_7.print(out, pageContext, false);
        out.write(_jsp_string2, 0, _jsp_string2.length);
        _caucho_expr_8.print(out, pageContext, false);
        out.write(_jsp_string2, 0, _jsp_string2.length);
        _caucho_expr_9.print(out, pageContext, false);
        out.write(_jsp_string2, 0, _jsp_string2.length);
        _caucho_expr_10.print(out, pageContext, false);
        out.write(_jsp_string2, 0, _jsp_string2.length);
        _caucho_expr_11.print(out, pageContext, false);
        out.write(_jsp_string3, 0, _jsp_string3.length);
      }
      pageContext.pageSetOrRemove("vo", _jsp_oldVar_1);
      out.write(_jsp_string4, 0, _jsp_string4.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -3988812337524854005L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("template/test1/list.jsp"), 4564749387958106203L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }
  private final static com.caucho.el.Expr _caucho_expr_0 =
    new com.caucho.el.IdExpr("list");
  private final static com.caucho.el.Expr _caucho_expr_1 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("vo"), new com.caucho.el.StringLiteral("a")), "vo.a");
  private final static com.caucho.el.Expr _caucho_expr_2 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("vo"), new com.caucho.el.StringLiteral("b")), "vo.b");
  private final static com.caucho.el.Expr _caucho_expr_3 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("vo"), new com.caucho.el.StringLiteral("theid")), "vo.theid");
  private final static com.caucho.el.Expr _caucho_expr_4 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("vo"), new com.caucho.el.StringLiteral("doubleTest")), "vo.doubleTest");
  private final static com.caucho.el.Expr _caucho_expr_5 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("vo"), new com.caucho.el.StringLiteral("dateTest")), "vo.dateTest");
  private final static com.caucho.el.Expr _caucho_expr_6 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("vo"), new com.caucho.el.StringLiteral("dateTimeTest")), "vo.dateTimeTest");
  private final static com.caucho.el.Expr _caucho_expr_7 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("vo"), new com.caucho.el.StringLiteral("timestameTest")), "vo.timestameTest");
  private final static com.caucho.el.Expr _caucho_expr_8 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("vo"), new com.caucho.el.StringLiteral("u")), "vo.u");
  private final static com.caucho.el.Expr _caucho_expr_9 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("vo"), new com.caucho.el.StringLiteral("uu")), "vo.uu");
  private final static com.caucho.el.Expr _caucho_expr_10 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("vo"), new com.caucho.el.StringLiteral("uuu")), "vo.uuu");
  private final static com.caucho.el.Expr _caucho_expr_11 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("vo"), new com.caucho.el.StringLiteral("o")), "vo.o");

  private final static char []_jsp_string2;
  private final static char []_jsp_string1;
  private final static char []_jsp_string4;
  private final static char []_jsp_string0;
  private final static char []_jsp_string3;
  static {
    _jsp_string2 = "</td>\r\n	<td>".toCharArray();
    _jsp_string1 = "\r\n	<tr>\r\n	<td>".toCharArray();
    _jsp_string4 = "\r\n</table>\r\n</body>\r\n</html>".toCharArray();
    _jsp_string0 = "\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n<title>Insert title here</title>\r\n</head>\r\n<body>\r\n<table>\r\n	<tr><td>a</td><td>b</td><td>theid</td><td>doubleTest</td><td>dateTest</td><td>dateTimeTest</td><td>timestameTest</td><td>u</td><td>uu</td><td>uuu</td><td>o</td></tr>	\r\n	".toCharArray();
    _jsp_string3 = "</td>\r\n	</tr>\r\n	".toCharArray();
  }
}
