/*
 * JSP generated by Resin-3.0.22 (built Mon, 13 Nov 2006 09:32:38 PST)
 */

package _jsp._template._test1;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _update__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=utf-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      _caucho_expr_0.print(out, pageContext, false);
      out.write(_jsp_string1, 0, _jsp_string1.length);
      _caucho_expr_1.print(out, pageContext, false);
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _caucho_expr_2.print(out, pageContext, false);
      out.write(_jsp_string3, 0, _jsp_string3.length);
      _caucho_expr_3.print(out, pageContext, false);
      out.write(_jsp_string4, 0, _jsp_string4.length);
      _caucho_expr_4.print(out, pageContext, false);
      out.write(_jsp_string5, 0, _jsp_string5.length);
      _caucho_expr_5.print(out, pageContext, false);
      out.write(_jsp_string6, 0, _jsp_string6.length);
      _caucho_expr_6.print(out, pageContext, false);
      out.write(_jsp_string7, 0, _jsp_string7.length);
      _caucho_expr_7.print(out, pageContext, false);
      out.write(_jsp_string8, 0, _jsp_string8.length);
      _caucho_expr_8.print(out, pageContext, false);
      out.write(_jsp_string9, 0, _jsp_string9.length);
      _caucho_expr_9.print(out, pageContext, false);
      out.write(_jsp_string10, 0, _jsp_string10.length);
      _caucho_expr_10.print(out, pageContext, false);
      out.write(_jsp_string11, 0, _jsp_string11.length);
      _caucho_expr_11.print(out, pageContext, false);
      out.write(_jsp_string12, 0, _jsp_string12.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -3988812337524854005L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("template/test1/update.jsp"), 4589015375781410089L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }
  private final static com.caucho.el.Expr _caucho_expr_0 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("vo"), new com.caucho.el.StringLiteral("id")), "vo.id");
  private final static com.caucho.el.Expr _caucho_expr_1 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("vo"), new com.caucho.el.StringLiteral("a")), "vo.a");
  private final static com.caucho.el.Expr _caucho_expr_2 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("vo"), new com.caucho.el.StringLiteral("b")), "vo.b");
  private final static com.caucho.el.Expr _caucho_expr_3 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("vo"), new com.caucho.el.StringLiteral("theid")), "vo.theid");
  private final static com.caucho.el.Expr _caucho_expr_4 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("vo"), new com.caucho.el.StringLiteral("doubleTest")), "vo.doubleTest");
  private final static com.caucho.el.Expr _caucho_expr_5 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("vo"), new com.caucho.el.StringLiteral("dateTest")), "vo.dateTest");
  private final static com.caucho.el.Expr _caucho_expr_6 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("vo"), new com.caucho.el.StringLiteral("dateTimeTest")), "vo.dateTimeTest");
  private final static com.caucho.el.Expr _caucho_expr_7 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("vo"), new com.caucho.el.StringLiteral("timestameTest")), "vo.timestameTest");
  private final static com.caucho.el.Expr _caucho_expr_8 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("vo"), new com.caucho.el.StringLiteral("u")), "vo.u");
  private final static com.caucho.el.Expr _caucho_expr_9 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("vo"), new com.caucho.el.StringLiteral("uu")), "vo.uu");
  private final static com.caucho.el.Expr _caucho_expr_10 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("vo"), new com.caucho.el.StringLiteral("uuu")), "vo.uuu");
  private final static com.caucho.el.Expr _caucho_expr_11 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("vo"), new com.caucho.el.StringLiteral("o")), "vo.o");

  private final static char []_jsp_string3;
  private final static char []_jsp_string5;
  private final static char []_jsp_string9;
  private final static char []_jsp_string7;
  private final static char []_jsp_string12;
  private final static char []_jsp_string8;
  private final static char []_jsp_string6;
  private final static char []_jsp_string0;
  private final static char []_jsp_string11;
  private final static char []_jsp_string2;
  private final static char []_jsp_string1;
  private final static char []_jsp_string10;
  private final static char []_jsp_string4;
  static {
    _jsp_string3 = "\"/></td></tr>\r\n		<tr><td>theid</td><td><input name=\"theid\" id=\"theid\" type=\"text\" value=\"".toCharArray();
    _jsp_string5 = "\"/></td></tr>\r\n		<tr><td>dateTest</td><td><input name=\"dateTest\" id=\"dateTest\" type=\"text\" value=\"".toCharArray();
    _jsp_string9 = "\"/></td></tr>\r\n		<tr><td>uu</td><td><input name=\"uu\" id=\"uu\" type=\"text\" value=\"".toCharArray();
    _jsp_string7 = "\"/></td></tr>\r\n		<tr><td>timestameTest</td><td><input name=\"timestameTest\" id=\"timestameTest\" type=\"text\" value=\"".toCharArray();
    _jsp_string12 = "\"/></td></tr>\r\n		<tr><td colspan=\"2\"><input type=\"submit\" value=\"\u4fee \u6539\" /></td></tr>\r\n	</table>\r\n</form>\r\n</body>\r\n</html>".toCharArray();
    _jsp_string8 = "\"/></td></tr>\r\n		<tr><td>u</td><td><input name=\"u\" id=\"u\" type=\"text\" value=\"".toCharArray();
    _jsp_string6 = "\"/></td></tr>\r\n		<tr><td>dateTimeTest</td><td><input name=\"dateTimeTest\" id=\"dateTimeTest\" type=\"text\" value=\"".toCharArray();
    _jsp_string0 = "\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n<title>Insert title here</title>\r\n</head>\r\n<body>\r\n<form action=\"/test1/updatepost.do\" method=\"post\">\r\n	<table>\r\n		<tr><td>id</td><td><input name=\"id\" id=\"id\" type=\"text\" value=\"".toCharArray();
    _jsp_string11 = "\"/></td></tr>\r\n		<tr><td>o</td><td><input name=\"o\" id=\"o\" type=\"text\" value=\"".toCharArray();
    _jsp_string2 = "\"/></td></tr>\r\n		<tr><td>b</td><td><input name=\"b\" id=\"b\" type=\"text\" value=\"".toCharArray();
    _jsp_string1 = "\"/></td></tr>\r\n		<tr><td>a</td><td><input name=\"a\" id=\"a\" type=\"text\" value=\"".toCharArray();
    _jsp_string10 = "\"/></td></tr>\r\n		<tr><td>uuu</td><td><input name=\"uuu\" id=\"uuu\" type=\"text\" value=\"".toCharArray();
    _jsp_string4 = "\"/></td></tr>\r\n		<tr><td>doubleTest</td><td><input name=\"doubleTest\" id=\"doubleTest\" type=\"text\" value=\"".toCharArray();
  }
}
